### PR TITLE
more tweaks needed to have a working package

### PR DESCRIPTION
**Pull request by bigio**

### CODE REVIEW

**Comment by extrafu** [comment]
Sign the CLA agreement.

**Comment by bigio** [comment]
It's signed, maybe not yet confirmed

**Comment by cgx** [comment]
Your single commit is associated to an email address that is not part of your profile. Fix this for this PR to be approved. Thanks!

**Comment by bigio** [comment]
thanks, email address confirmed

**Comment by extrafu** [comment]
This PR is no longer relevant.

**Pull request closed without merging**
