### PR TITLE
Remove incomplete Czech localization

### PR DESCRIPTION
**Pull request by MikkCZ**
We've received a report that your extension is broken in Thunderbird 68 (YSOD = yellow screen of death), in Czech version only. A brief investigation lead me to the cause, which is incomplete Czech localization with missing entities, which cause the YSOD. Luckily, it's just a part of the window, not the whole Thunderbird.

error-sogo68

I propose to remove the outdated localization (this PR) as a quick fix. Please let me know when is the earliest time you could release the new version, so I notify the reported they should update the extension.

### CODE REVIEW

**Comment by extrafu** [comment]
Let's fix the localization instead - it's a lot easier than to pull back all those files and modifications.

**Comment by MikkCZ** [comment]
> Let's fix the localization instead - it's a lot easier than to pull back all those files and modifications.

Well, reverting a single commit should not be that hard. There is also not much in the current localization. Also if I look at the files, there are about 20 of them totally missing.

I do localize to Czech, but I have full hands with Mozilla projects themselves. Do you have Czech localizer by hand? Alternatively the missing strings and files can be populated by English original as an explicit fallback. Of course mixed languages in the UI are always bad UX and mixed languages in l10n files are harder to identify compared to completely missing ones.

**Comment by extrafu** [comment]
That's the plan, use the English fallback. Anyone with TB in Czech could do that in a couple of minutes. I might do it tomorrow.

**Comment by MikkCZ** [comment]
Closing in favour of #7 .

**Pull request closed without merging**
